- name: Print runner & terraform info
  working-directory: ./environments/dev
  run: |
    terraform version
    echo "Workspace: $(terraform workspace show || echo default)"

- name: Terraform Init
  working-directory: ./environments/dev
  env:
    TF_IN_AUTOMATION: "1"
    TF_LOG: "TRACE"
    TF_LOG_PATH: tf.log
  run: |
    set -o pipefail
    terraform init -input=false -no-color -upgrade

- name: Terraform Validate
  working-directory: ./environments/dev
  env:
    TF_IN_AUTOMATION: "1"
    TF_LOG: "TRACE"
    TF_LOG_PATH: tf.log
  run: |
    terraform validate -no-color -var-file=terraform.tfvars

- name: Terraform Format
  working-directory: ./environments/dev
  run: terraform fmt -check -recursive

- name: Terraform Plan
  working-directory: ./environments/dev
  env:
    TF_IN_AUTOMATION: "1"
    TF_LOG: "TRACE"
    TF_LOG_PATH: tf.log
  run: |
    set -o pipefail
    terraform plan -input=false -no-color -var-file=terraform.tfvars -out=tfplan || (echo "PLAN FAILED — imprimiendo tf.log" && sed -n '1,400p' tf.log && exit 1)

- name: Upload Terraform debug log
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: terraform-debug-log
    path: ./environments/dev/tf.log

- name: Terraform Apply
  if: success()
  working-directory: ./environments/dev
  env:
    TF_IN_AUTOMATION: "1"
  run: terraform apply -auto-approve tfplan